<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DataAcuanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('data_acuan')->insert([
            [
                'usia' => 3,
                'TB-L_min' => 58.4,
                'TB-P_min' => 57,
                'BB-L_min' => 5.8,
                'BB-P_min' => 5.3,
                'LB-L_min' => 33.0,
                'LB-P_min' => 32.7,
            ],
            [
                'usia' => 4,
                'TB-L_min' => 60,
                'TB-P_min' => 58.5,
                'BB-L_min' => 6.2,
                'BB-P_min' => 5.8,
                'LB-L_min' => 34.5,
                'LB-P_min' => 34.0,
            ],
            [
                'usia' => 5,
                'TB-L_min' => 61.5,
                'TB-P_min' => 60,
                'BB-L_min' => 6.7,
                'BB-P_min' => 6.2,
                'LB-L_min' => 36.0,
                'LB-P_min' => 35.3,
            ],
            [
                'usia' => 6,
                'TB-L_min' => 64.8,
                'TB-P_min' => 62.5,
                'BB-L_min' => 7.3,
                'BB-P_min' => 6.7,
                'LB-L_min' => 37.5,
                'LB-P_min' => 36.7,
            ],
            [
                'usia' => 7,
                'TB-L_min' => 66.0,
                'TB-P_min' => 63.7,
                'BB-L_min' => 7.6,
                'BB-P_min' => 6.9,
                'LB-L_min' => 38.0,
                'LB-P_min' => 37.3,
            ],
            [
                'usia' => 8,
                'TB-L_min' => 67.5,
                'TB-P_min' => 65.0,
                'BB-L_min' => 7.9,
                'BB-P_min' => 7.2,
                'LB-L_min' => 38.5,
                'LB-P_min' => 37.8,
            ],
            [
                'usia' => 9,
                'TB-L_min' => 69.2,
                'TB-P_min' => 67.4,
                'BB-L_min' => 8.0,
                'BB-P_min' => 7.3,
                'LB-L_min' => 39.0,
                'LB-P_min' => 38.3,
            ],
            [
                'usia' => 10,
                'TB-L_min' => 70.7,
                'TB-P_min' => 68.6,
                'BB-L_min' => 8.5,
                'BB-P_min' => 7.7,
                'LB-L_min' => 39.5,
                'LB-P_min' => 38.8,
            ],
            [
                'usia' => 11,
                'TB-L_min' => 72.1,
                'TB-P_min' => 70.0,
                'BB-L_min' => 8.7,
                'BB-P_min' => 7.8,
                'LB-L_min' => 40.0,
                'LB-P_min' => 39.3,
            ],
            [
                'usia' => 12,
                'TB-L_min' => 72.7,
                'TB-P_min' => 70.6,
                'BB-L_min' => 8.9,
                'BB-P_min' => 8.1,
                'LB-L_min' => 40.5,
                'LB-P_min' => 39.8,
            ],
            [
                'usia' => 13,
                'TB-L_min' => 73.9,
                'TB-P_min' => 71.8,
                'BB-L_min' => 9.0,
                'BB-P_min' => 8.2,
                'LB-L_min' => 41.0,
                'LB-P_min' => 40.3,
            ],
            [
                'usia' => 14,
                'TB-L_min' => 75.2,
                'TB-P_min' => 73.1,
                'BB-L_min' => 9.3,
                'BB-P_min' => 8.4,
                'LB-L_min' => 41.5,
                'LB-P_min' => 40.8,
            ],
            [
                'usia' => 15,
                'TB-L_min' => 76.4,
                'TB-P_min' => 74.4,
                'BB-L_min' => 9.6,
                'BB-P_min' => 8.6,
                'LB-L_min' => 42.0,
                'LB-P_min' => 41.3,
            ],
            [
                'usia' => 16,
                'TB-L_min' => 77.6,
                'TB-P_min' => 75.6,
                'BB-L_min' => 9.8,
                'BB-P_min' => 8.7,
                'LB-L_min' => 42.5,
                'LB-P_min' => 41.8,
            ],
            [
                'usia' => 17,
                'TB-L_min' => 78.7,
                'TB-P_min' => 76.8,
                'BB-L_min' => 10.0,
                'BB-P_min' => 8.9,
                'LB-L_min' => 43.0,
                'LB-P_min' => 42.3,
            ],
            [
                'usia' => 18,
                'TB-L_min' => 77.7,
                'TB-P_min' => 75.0,
                'BB-L_min' => 10.3,
                'BB-P_min' => 8.9,
                'LB-L_min' => 43.5,
                'LB-P_min' => 42.8,
            ],
            [
                'usia' => 19,
                'TB-L_min' => 80.7,
                'TB-P_min' => 78.1,
                'BB-L_min' => 10.5,
                'BB-P_min' => 9.1,
                'LB-L_min' => 44.0,
                'LB-P_min' => 43.3,
            ],
            [
                'usia' => 20,
                'TB-L_min' => 81.8,
                'TB-P_min' => 79.2,
                'BB-L_min' => 10.7,
                'BB-P_min' => 9.3,
                'LB-L_min' => 44.5,
                'LB-P_min' => 43.8,
            ],
            [
                'usia' => 21,
                'TB-L_min' => 82.8,
                'TB-P_min' => 80.2,
                'BB-L_min' => 10.8,
                'BB-P_min' => 9.4,
                'LB-L_min' => 45.0,
                'LB-P_min' => 44.3,
            ],
            [
                'usia' => 22,
                'TB-L_min' => 83.8,
                'TB-P_min' => 81.2,
                'BB-L_min' => 11.0,
                'BB-P_min' => 9.5,
                'LB-L_min' => 45.5,
                'LB-P_min' => 44.8,
            ],
            [
                'usia' => 23,
                'TB-L_min' => 84.9,
                'TB-P_min' => 82.3,
                'BB-L_min' => 11.2,
                'BB-P_min' => 9.6,
                'LB-L_min' => 46.0,
                'LB-P_min' => 45.3,
            ],
            [
                'usia' => 24,
                'TB-L_min' => 82.3,
                'TB-P_min' => 79.5,
                'BB-L_min' => 11.3,
                'BB-P_min' => 9.7,
                'LB-L_min' => 46.5,
                'LB-P_min' => 45.8,
            ],
            [
                'usia' => 25,
                'TB-L_min' => 86.8,
                'TB-P_min' => 84.1,
                'BB-L_min' => 11.5,
                'BB-P_min' => 9.8,
                'LB-L_min' => 47.0,
                'LB-P_min' => 46.3,
            ],
            [
                'usia' => 26,
                'TB-L_min' => 87.7,
                'TB-P_min' => 11.6,
                'BB-L_min' => 11.6,
                'BB-P_min' => 9.9,
                'LB-L_min' => 48.5,
                'LB-P_min' => 48.1,
            ],
            [
                'usia' => 27,
                'TB-L_min' => 88.6,
                'TB-P_min' => 86.0,
                'BB-L_min' => 11.8,
                'BB-P_min' => 10.0,
                'LB-L_min' => 48.7,
                'LB-P_min' => 48.3,
            ],
            [
                'usia' => 28,
                'TB-L_min' => 89.5,
                'TB-P_min' => 86.9,
                'BB-L_min' => 11.9,
                'BB-P_min' => 10.1,
                'LB-L_min' => 48.9,
                'LB-P_min' => 48.5,
            ],
            [
                'usia' => 29,
                'TB-L_min' => 90.3,
                'TB-P_min' => 87.8,
                'BB-L_min' => 12.0,
                'BB-P_min' => 10.2,
                'LB-L_min' => 49.1,
                'LB-P_min' => 48.7,
            ],
            [
                'usia' => 30,
                'TB-L_min' => 91.2,
                'TB-P_min' => 88.7,
                'BB-L_min' => 12.1,
                'BB-P_min' => 10.3,
                'LB-L_min' => 49.3,
                'LB-P_min' => 48.9,
            ],
            [
                'usia' => 31,
                'TB-L_min' => 92.0,
                'TB-P_min' => 89.5,
                'BB-L_min' => 12.2,
                'BB-P_min' => 10.4,
                'LB-L_min' => 49.5,
                'LB-P_min' => 49.1,
            ],
            [
                'usia' => 32,
                'TB-L_min' => 92.8,
                'TB-P_min' => 90.3,
                'BB-L_min' => 12.4,
                'BB-P_min' => 10.5,
                'LB-L_min' => 49.7,
                'LB-P_min' => 49.3,
            ],
            [
                'usia' => 33,
                'TB-L_min' => 93.6,
                'TB-P_min' => 91.2,
                'BB-L_min' => 12.5,
                'BB-P_min' => 10.6,
                'LB-L_min' => 49.9,
                'LB-P_min' => 49.5,
            ],
            [
                'usia' => 34,
                'TB-L_min' => 94.4,
                'TB-P_min' => 92.0,
                'BB-L_min' => 12.6,
                'BB-P_min' => 10.7,
                'LB-L_min' => 50.1,
                'LB-P_min' => 49.7,
            ],
            [
                'usia' => 35,
                'TB-L_min' => 95.1,
                'TB-P_min' => 92.8,
                'BB-L_min' => 12.7,
                'BB-P_min' => 10.8,
                'LB-L_min' => 50.3,
                'LB-P_min' => 49.9,
            ],
            [
                'usia' => 36,
                'TB-L_min' => 95.9,
                'TB-P_min' => 93.6,
                'BB-L_min' => 12.8,
                'BB-P_min' => 10.9,
                'LB-L_min' => 50.6,
                'LB-P_min' => 50.2,
            ],
            [
                'usia' => 37,
                'TB-L_min' => 96.6,
                'TB-P_min' => 94.4,
                'BB-L_min' => 12.9,
                'BB-P_min' => 11.0,
                'LB-L_min' => 50.8,
                'LB-P_min' => 50.4,
            ],
            [
                'usia' => 38,
                'TB-L_min' => 97.4,
                'TB-P_min' => 95.2,
                'BB-L_min' => 13.0,
                'BB-P_min' => 11.1,
                'LB-L_min' => 51.0,
                'LB-P_min' => 50.6,
            ],
            [
                'usia' => 39,
                'TB-L_min' => 98.1,
                'TB-P_min' => 96.0,
                'BB-L_min' => 13.1,
                'BB-P_min' => 11.2,
                'LB-L_min' => 51.2,
                'LB-P_min' => 50.8,
            ],
            [
                'usia' => 40,
                'TB-L_min' => 98.8,
                'TB-P_min' => 96.7,
                'BB-L_min' => 13.2,
                'BB-P_min' => 11.3,
                'LB-L_min' => 51.4,
                'LB-P_min' => 51.0,
            ],
            [
                'usia' => 41,
                'TB-L_min' => 99.5,
                'TB-P_min' => 97.5,
                'BB-L_min' => 13.3,
                'BB-P_min' => 11.4,
                'LB-L_min' => 51.6,
                'LB-P_min' => 51.2,
            ],
            [
                'usia' => 42,
                'TB-L_min' => 100.2,
                'TB-P_min' => 98.3,
                'BB-L_min' => 13.4,
                'BB-P_min' => 11.5,
                'LB-L_min' => 51.8,
                'LB-P_min' => 51.4,
            ],
            [
                'usia' => 43,
                'TB-L_min' => 100.9,
                'TB-P_min' => 99.0,
                'BB-L_min' => 13.5,
                'BB-P_min' => 11.6,
                'LB-L_min' => 52.0,
                'LB-P_min' => 51.6,
            ],
            [
                'usia' => 44,
                'TB-L_min' => 101.6,
                'TB-P_min' => 99.8,
                'BB-L_min' => 13.6,
                'BB-P_min' => 11.7,
                'LB-L_min' => 52.2,
                'LB-P_min' => 51.8,
            ],
            [
                'usia' => 45,
                'TB-L_min' => 102.3,
                'TB-P_min' => 100.5,
                'BB-L_min' => 13.7,
                'BB-P_min' => 11.8,
                'LB-L_min' => 52.4,
                'LB-P_min' => 52.0,
            ],
            [
                'usia' => 46,
                'TB-L_min' => 103.0,
                'TB-P_min' => 101.3,
                'BB-L_min' => 13.8,
                'BB-P_min' => 11.9,
                'LB-L_min' => 52.6,
                'LB-P_min' => 52.2,
            ],
            [
                'usia' => 47,
                'TB-L_min' => 103.7,
                'TB-P_min' => 102.0,
                'BB-L_min' => 13.9,
                'BB-P_min' => 12.0,
                'LB-L_min' => 52.8,
                'LB-P_min' => 52.4,
            ],
            [
                'usia' => 48,
                'TB-L_min' => 104.4,
                'TB-P_min' => 102.8,
                'BB-L_min' => 14.0,
                'BB-P_min' => 12.1,
                'LB-L_min' => 53.0,
                'LB-P_min' => 52.6,
            ],
            [
                'usia' => 49,
                'TB-L_min' => 105.1,
                'TB-P_min' => 103.5,
                'BB-L_min' => 14.1,
                'BB-P_min' => 12.2,
                'LB-L_min' => 53.2,
                'LB-P_min' => 52.8,
            ],
            [
                'usia' => 50,
                'TB-L_min' => 105.7,
                'TB-P_min' => 104.2,
                'BB-L_min' => 14.2,
                'BB-P_min' => 12.3,
                'LB-L_min' => 53.4,
                'LB-P_min' => 53.0,
            ],
            [
                'usia' => 51,
                'TB-L_min' => 106.4,
                'TB-P_min' => 105.0,
                'BB-L_min' => 14.3,
                'BB-P_min' => 12.4,
                'LB-L_min' => 53.6,
                'LB-P_min' => 53.2,
            ],
            [
                'usia' => 52,
                'TB-L_min' => 107.1,
                'TB-P_min' => 105.7,
                'BB-L_min' => 14.4,
                'BB-P_min' => 12.5,
                'LB-L_min' => 53.8,
                'LB-P_min' => 53.4,
            ],
            [
                'usia' => 53,
                'TB-L_min' => 107.7,
                'TB-P_min' => 106.4,
                'BB-L_min' => 14.5,
                'BB-P_min' => 12.6,
                'LB-L_min' => 54.0,
                'LB-P_min' => 53.6,
            ],
            [
                'usia' => 54,
                'TB-L_min' => 108.3,
                'TB-P_min' => 107.1,
                'BB-L_min' => 14.6,
                'BB-P_min' => 12.7,
                'LB-L_min' => 54.2,
                'LB-P_min' => 53.8,
            ],
            [
                'usia' => 55,
                'TB-L_min' => 108.9,
                'TB-P_min' => 107.8,
                'BB-L_min' => 14.7,
                'BB-P_min' => 12.8,
                'LB-L_min' => 54.4,
                'LB-P_min' => 54.0,
            ],
            [
                'usia' => 56,
                'TB-L_min' => 109.5,
                'TB-P_min' => 108.5,
                'BB-L_min' => 14.8,
                'BB-P_min' => 12.9,
                'LB-L_min' => 54.6,
                'LB-P_min' => 54.2,
            ],
            [
                'usia' => 57,
                'TB-L_min' => 110.1,
                'TB-P_min' => 109.2,
                'BB-L_min' => 14.9,
                'BB-P_min' => 13.0,
                'LB-L_min' => 54.8,
                'LB-P_min' => 54.4,
            ],
            [
                'usia' => 58,
                'TB-L_min' => 110.7,
                'TB-P_min' => 109.8,
                'BB-L_min' => 15.0,
                'BB-P_min' => 13.1,
                'LB-L_min' => 55.0,
                'LB-P_min' => 54.6,
            ],
            [
                'usia' => 59,
                'TB-L_min' => 111.3,
                'TB-P_min' => 110.5,
                'BB-L_min' => 15.1,
                'BB-P_min' => 13.2,
                'LB-L_min' => 55.2,
                'LB-P_min' => 54.8,
            ],
            [
                'usia' => 60,
                'TB-L_min' => 111.9,
                'TB-P_min' => 111.2,
                'BB-L_min' => 15.2,
                'BB-P_min' => 13.3,
                'LB-L_min' => 55.4,
                'LB-P_min' => 55.0,
            ],
        ]);        
    }
}
