<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DataAcuanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('data_acuan')->insert([
            [
                'usia' => 3,
                'BB-L_min' => 5.8,
                'BB-L_max' => 7.5,
                'BB-P_min' => 5.3,
                'BB-P_max' => 7,
                'TB-L_min' => 58.4,
                'TB-L_max' => 64,
                'TB-P_min' => 57,
                'TB-P_max' => 62.6,
                'LK-L_min' => 39.1,
                'LK-L_max' => 41.6,
                'LK-P_min' => 38.2,
                'LK-P_max' => 40.9,
            ],
            [
                'usia' => 4,
                'BB-L_min' => 6.2,
                'BB-L_max' => 7.9,
                'BB-P_min' => 5.8,
                'BB-P_max' => 7.4,
                'TB-L_min' => 60,
                'TB-L_max' => 65.8,
                'TB-P_min' => 58.5,
                'TB-P_max' => 64.3,
                'LK-L_min' => 40,
                'LK-L_max' => 42.4,
                'LK-P_min' => 39.1,
                'LK-P_max' => 41.7,
            ],
            [
                'usia' => 5,
                'BB-L_min' => 6.7,
                'BB-L_max' => 8.4,
                'BB-P_min' => 6.2,
                'BB-P_max' => 7.9,
                'TB-L_min' => 61.5,
                'TB-L_max' => 67.6,
                'TB-P_min' => 60.0,
                'TB-P_max' => 66.0,
                'LK-L_min' => 40.9,
                'LK-L_max' => 43.2,
                'LK-P_min' => 40.0,
                'LK-P_max' => 42.5,
            ],
            [
                'usia' => 6,
                'BB-L_min' => 7.3,
                'BB-L_max' => 8.8,
                'BB-P_min' => 6.7,
                'BB-P_max' => 8.3,
                'TB-L_min' => 64.8,
                'TB-L_max' => 70.5,
                'TB-P_min' => 62.5,
                'TB-P_max' => 68.7,
                'LK-L_min' => 41.5,
                'LK-L_max' => 43.5,
                'LK-P_min' => 40.8,
                'LK-P_max' => 43.0,
            ],
            [
                'usia' => 7,
                'BB-L_min' => 7.6,
                'BB-L_max' => 9.2,
                'BB-P_min' => 6.9,
                'BB-P_max' => 8.7,
                'TB-L_min' => 66.0,
                'TB-L_max' => 72.4,
                'TB-P_min' => 63.7,
                'TB-P_max' => 70.3,
                'LK-L_min' => 42.0,
                'LK-L_max' => 44.0,
                'LK-P_min' => 41.3,
                'LK-P_max' => 43.5,
            ],
            [
                'usia' => 8,
                'BB-L_min' => 7.9,
                'BB-L_max' => 9.6,
                'BB-P_min' => 7.2,
                'BB-P_max' => 9.0,
                'TB-L_min' => 67.5,
                'TB-L_max' => 74.2,
                'TB-P_min' => 65.0,
                'TB-P_max' => 71.9,
                'LK-L_min' => 42.3,
                'LK-L_max' => 44.3,
                'LK-P_min' => 41.7,
                'LK-P_max' => 43.9,
            ],
            [
                'usia' => 9,
                'BB-L_min' => 8.0,
                'BB-L_max' => 9.8,
                'BB-P_min' => 7.3,
                'BB-P_max' => 9.2,
                'TB-L_min' => 69.2,
                'TB-L_max' => 75.5,
                'TB-P_min' => 67.4,
                'TB-P_max' => 73.7,
                'LK-L_min' => 42.8,
                'LK-L_max' => 45.0,
                'LK-P_min' => 42.2,
                'LK-P_max' => 44.4,
            ],
            [
                'usia' => 10,
                'BB-L_min' => 8.5,
                'BB-L_max' => 10.3,
                'BB-P_min' => 7.7,
                'BB-P_max' => 9.6,
                'TB-L_min' => 70.7,
                'TB-L_max' => 77.0,
                'TB-P_min' => 68.6,
                'TB-P_max' => 75.3,
                'LK-L_min' => 43.0,
                'LK-L_max' => 45.2,
                'LK-P_min' => 42.5,
                'LK-P_max' => 44.7,
            ],
            [
                'usia' => 11,
                'BB-L_min' => 8.7,
                'BB-L_max' => 10.6,
                'BB-P_min' => 7.8,
                'BB-P_max' => 9.9,
                'TB-L_min' => 72.1,
                'TB-L_max' => 78.4,
                'TB-P_min' => 70.0,
                'TB-P_max' => 76.8,
                'LK-L_min' => 43.3,
                'LK-L_max' => 45.5,
                'LK-P_min' => 42.8,
                'LK-P_max' => 45.0,
            ],
            [
                'usia' => 12,
                'BB-L_min' => 8.9,
                'BB-L_max' => 10.7,
                'BB-P_min' => 8.1,
                'BB-P_max' => 10.0,
                'TB-L_min' => 72.7,
                'TB-L_max' => 79.7,
                'TB-P_min' => 70.6,
                'TB-P_max' => 77.8,
                'LK-L_min' => 43.8,
                'LK-L_max' => 46.0,
                'LK-P_min' => 43.1,
                'LK-P_max' => 45.4,
            ],
            [
                'usia' => 13,
                'BB-L_min' => 9.0,
                'BB-L_max' => 10.9,
                'BB-P_min' => 8.2,
                'BB-P_max' => 10.2,
                'TB-L_min' => 73.9,
                'TB-L_max' => 80.9,
                'TB-P_min' => 71.8,
                'TB-P_max' => 79.1,
                'LK-L_min' => 44.0,
                'LK-L_max' => 46.3,
                'LK-P_min' => 43.3,
                'LK-P_max' => 45.6,
            ],
            [
                'usia' => 14,
                'BB-L_min' => 9.3,
                'BB-L_max' => 11.2,
                'BB-P_min' => 8.4,
                'BB-P_max' => 10.5,
                'TB-L_min' => 75.2,
                'TB-L_max' => 82.1,
                'TB-P_min' => 73.1,
                'TB-P_max' => 80.3,
                'LK-L_min' => 44.3,
                'LK-L_max' => 46.5,
                'LK-P_min' => 43.5,
                'LK-P_max' => 45.9,
            ],
            [
                'usia' => 15,
                'BB-L_min' => 9.6,
                'BB-L_max' => 11.5,
                'BB-P_min' => 8.6,
                'BB-P_max' => 10.8,
                'TB-L_min' => 76.4,
                'TB-L_max' => 83.4,
                'TB-P_min' => 74.4,
                'TB-P_max' => 81.7,
                'LK-L_min' => 44.5,
                'LK-L_max' => 46.8,
                'LK-P_min' => 43.7,
                'LK-P_max' => 46.1,
            ],
            [
                'usia' => 16,
                'BB-L_min' => 9.8,
                'BB-L_max' => 11.7,
                'BB-P_min' => 8.7,
                'BB-P_max' => 11.0,
                'TB-L_min' => 77.6,
                'TB-L_max' => 84.5,
                'TB-P_min' => 75.6,
                'TB-P_max' => 82.9,
                'LK-L_min' => 44.8,
                'LK-L_max' => 47.0,
                'LK-P_min' => 43.9,
                'LK-P_max' => 46.4,
            ],
            [
                'usia' => 17,
                'BB-L_min' => 10.0,
                'BB-L_max' => 11.9,
                'BB-P_min' => 8.9,
                'BB-P_max' => 11.2,
                'TB-L_min' => 78.7,
                'TB-L_max' => 85.7,
                'TB-P_min' => 76.8,
                'TB-P_max' => 84.1,
                'LK-L_min' => 45.0,
                'LK-L_max' => 47.3,
                'LK-P_min' => 44.1,
                'LK-P_max' => 46.6,
            ],
            [
                'usia' => 18,
                'BB-L_min' => 10.3,
                'BB-L_max' => 12.2,
                'BB-P_min' => 8.9,
                'BB-P_max' => 11.5,
                'TB-L_min' => 77.7,
                'TB-L_max' => 85.1,
                'TB-P_min' => 75.0,
                'TB-P_max' => 82.6,
                'LK-L_min' => 45.2,
                'LK-L_max' => 47.3,
                'LK-P_min' => 44.4,
                'LK-P_max' => 46.6,
            ],
            [
                'usia' => 19,
                'BB-L_min' => 10.5,
                'BB-L_max' => 12.5,
                'BB-P_min' => 9.1,
                'BB-P_max' => 11.8,
                'TB-L_min' => 80.7,
                'TB-L_max' => 87.8,
                'TB-P_min' => 78.1,
                'TB-P_max' => 85.4,
                'LK-L_min' => 45.4,
                'LK-L_max' => 47.5,
                'LK-P_min' => 44.5,
                'LK-P_max' => 46.8,
            ],
            [
                'usia' => 20,
                'BB-L_min' => 10.7,
                'BB-L_max' => 12.7,
                'BB-P_min' => 9.3,
                'BB-P_max' => 12.0,
                'TB-L_min' => 81.8,
                'TB-L_max' => 89.0,
                'TB-P_min' => 79.2,
                'TB-P_max' => 86.6,
                'LK-L_min' => 45.6,
                'LK-L_max' => 47.7,
                'LK-P_min' => 44.8,
                'LK-P_max' => 47.1,
            ],
            [
                'usia' => 21,
                'BB-L_min' => 10.8,
                'BB-L_max' => 12.9,
                'BB-P_min' => 9.4,
                'BB-P_max' => 12.2,
                'TB-L_min' => 82.8,
                'TB-L_max' => 90.2,
                'TB-P_min' => 80.2,
                'TB-P_max' => 87.7,
                'LK-L_min' => 45.8,
                'LK-L_max' => 47.9,
                'LK-P_min' => 45.0,
                'LK-P_max' => 47.3,
            ],
            [
                'usia' => 22,
                'BB-L_min' => 11.0,
                'BB-L_max' => 13.2,
                'BB-P_min' => 9.5,
                'BB-P_max' => 12.5,
                'TB-L_min' => 83.8,
                'TB-L_max' => 91.4,
                'TB-P_min' => 81.2,
                'TB-P_max' => 88.8,
                'LK-L_min' => 45.9,
                'LK-L_max' => 48.0,
                'LK-P_min' => 45.1,
                'LK-P_max' => 47.5,
            ],
            [
                'usia' => 23,
                'BB-L_min' => 11.2,
                'BB-L_max' => 13.4,
                'BB-P_min' => 9.6,
                'BB-P_max' => 12.7,
                'TB-L_min' => 84.9,
                'TB-L_max' => 92.6,
                'TB-P_min' => 82.3,
                'TB-P_max' => 90.0,
                'LK-L_min' => 46.0,
                'LK-L_max' => 48.2,
                'LK-P_min' => 45.3,
                'LK-P_max' => 47.7,
            ],
            [
                'usia' => 24,
                'BB-L_min' => 11.3,
                'BB-L_max' => 13.6,
                'BB-P_min' => 9.7,
                'BB-P_max' => 12.9,
                'TB-L_min' => 82.3,
                'TB-L_max' => 90.0,
                'TB-P_min' => 79.5,
                'TB-P_max' => 87.4,
                'LK-L_min' => 46.1,
                'LK-L_max' => 48.4,
                'LK-P_min' => 45.4,
                'LK-P_max' => 47.6,
            ],
            [
                'usia' => 25,
                'BB-L_min' => 11.5,
                'BB-L_max' => 13.8,
                'BB-P_min' => 9.8,
                'BB-P_max' => 13.2,
                'TB-L_min' => 86.8,
                'TB-L_max' => 94.5,
                'TB-P_min' => 84.1,
                'TB-P_max' => 92.1,
                'LK-L_min' => 46.2,
                'LK-L_max' => 48.5,
                'LK-P_min' => 45.5,
                'LK-P_max' => 47.8,
            ],
            [
                'usia' => 26,
                'BB-L_min' => 11.6,
                'BB-L_max' => 14.0,
                'BB-P_min' => 9.9,
                'BB-P_max' => 13.4,
                'TB-L_min' => 87.7,
                'TB-L_max' => 95.4,
                'TB-P_min' => 85.1,
                'TB-P_max' => 93.1,
                'LK-L_min' => 46.3,
                'LK-L_max' => 48.6,
                'LK-P_min' => 45.6,
                'LK-P_max' => 47.9,
            ],
            [
                'usia' => 27,
                'BB-L_min' => 11.8,
                'BB-L_max' => 14.2,
                'BB-P_min' => 10.0,
                'BB-P_max' => 13.6,
                'TB-L_min' => 88.6,
                'TB-L_max' => 96.3,
                'TB-P_min' => 86.0,
                'TB-P_max' => 94.0,
                'LK-L_min' => 46.4,
                'LK-L_max' => 48.7,
                'LK-P_min' => 45.7,
                'LK-P_max' => 48.0,
            ],
            [
                'usia' => 28,
                'BB-L_min' => 11.9,
                'BB-L_max' => 14.4,
                'BB-P_min' => 10.1,
                'BB-P_max' => 13.8,
                'TB-L_min' => 89.5,
                'TB-L_max' => 97.2,
                'TB-P_min' => 86.9,
                'TB-P_max' => 94.9,
                'LK-L_min' => 46.5,
                'LK-L_max' => 48.8,
                'LK-P_min' => 45.8,
                'LK-P_max' => 48.1,
            ],
            [
                'usia' => 29,
                'BB-L_min' => 12.0,
                'BB-L_max' => 14.6,
                'BB-P_min' => 10.2,
                'BB-P_max' => 14.0,
                'TB-L_min' => 90.3,
                'TB-L_max' => 98.1,
                'TB-P_min' => 87.8,
                'TB-P_max' => 95.9,
                'LK-L_min' => 46.6,
                'LK-L_max' => 48.9,
                'LK-P_min' => 45.9,
                'LK-P_max' => 48.2,
            ],
            [
                'usia' => 30,
                'BB-L_min' => 12.1,
                'BB-L_max' => 14.8,
                'BB-P_min' => 10.3,
                'BB-P_max' => 14.2,
                'TB-L_min' => 91.2,
                'TB-L_max' => 98.9,
                'TB-P_min' => 88.7,
                'TB-P_max' => 96.8,
                'LK-L_min' => 46.7,
                'LK-L_max' => 49.0,
                'LK-P_min' => 46.0,
                'LK-P_max' => 48.3,
            ],
            [
                'usia' => 31,
                'BB-L_min' => 12.2,
                'BB-L_max' => 15.0,
                'BB-P_min' => 10.4,
                'BB-P_max' => 14.4,
                'TB-L_min' => 92.0,
                'TB-L_max' => 99.8,
                'TB-P_min' => 89.5,
                'TB-P_max' => 97.7,
                'LK-L_min' => 46.8,
                'LK-L_max' => 49.1,
                'LK-P_min' => 46.1,
                'LK-P_max' => 48.4,
            ],
            [
                'usia' => 32,
                'BB-L_min' => 12.4,
                'BB-L_max' => 15.2,
                'BB-P_min' => 10.5,
                'BB-P_max' => 14.6,
                'TB-L_min' => 92.8,
                'TB-L_max' => 100.6,
                'TB-P_min' => 90.3,
                'TB-P_max' => 98.6,
                'LK-L_min' => 46.9,
                'LK-L_max' => 49.2,
                'LK-P_min' => 46.2,
                'LK-P_max' => 48.5,
            ],
            [
                'usia' => 33,
                'BB-L_min' => 12.5,
                'BB-L_max' => 15.4,
                'BB-P_min' => 10.6,
                'BB-P_max' => 14.8,
                'TB-L_min' => 93.6,
                'TB-L_max' => 101.4,
                'TB-P_min' => 91.2,
                'TB-P_max' => 99.5,
                'LK-L_min' => 47.0,
                'LK-L_max' => 49.3,
                'LK-P_min' => 46.3,
                'LK-P_max' => 48.6,
            ],
            [
                'usia' => 34,
                'BB-L_min' => 12.6,
                'BB-L_max' => 15.6,
                'BB-P_min' => 10.7,
                'BB-P_max' => 15.0,
                'TB-L_min' => 94.4,
                'TB-L_max' => 102.3,
                'TB-P_min' => 92.0,
                'TB-P_max' => 100.4,
                'LK-L_min' => 47.1,
                'LK-L_max' => 49.4,
                'LK-P_min' => 46.4,
                'LK-P_max' => 48.7,
            ],
            [
                'usia' => 35,
                'BB-L_min' => 12.7,
                'BB-L_max' => 15.8,
                'BB-P_min' => 10.8,
                'BB-P_max' => 15.2,
                'TB-L_min' => 95.1,
                'TB-L_max' => 103.1,
                'TB-P_min' => 92.8,
                'TB-P_max' => 101.2,
                'LK-L_min' => 47.2,
                'LK-L_max' => 49.5,
                'LK-P_min' => 46.5,
                'LK-P_max' => 48.8,
            ],
            [
                'usia' => 36,
                'BB-L_min' => 12.8,
                'BB-L_max' => 16.0,
                'BB-P_min' => 10.9,
                'BB-P_max' => 15.4,
                'TB-L_min' => 95.9,
                'TB-L_max' => 103.9,
                'TB-P_min' => 93.6,
                'TB-P_max' => 102.0,
                'LK-L_min' => 47.3,
                'LK-L_max' => 49.6,
                'LK-P_min' => 46.6,
                'LK-P_max' => 48.9,
            ],
            [
                'usia' => 37,
                'BB-L_min' => 12.9,
                'BB-L_max' => 16.1,
                'BB-P_min' => 11.0,
                'BB-P_max' => 15.5,
                'TB-L_min' => 96.6,
                'TB-L_max' => 104.7,
                'TB-P_min' => 94.4,
                'TB-P_max' => 102.9,
                'LK-L_min' => 47.4,
                'LK-L_max' => 49.7,
                'LK-P_min' => 46.7,
                'LK-P_max' => 49.0,
            ],
            [
                'usia' => 38,
                'BB-L_min' => 13.0,
                'BB-L_max' => 16.3,
                'BB-P_min' => 11.1,
                'BB-P_max' => 15.7,
                'TB-L_min' => 97.4,
                'TB-L_max' => 105.5,
                'TB-P_min' => 95.2,
                'TB-P_max' => 103.7,
                'LK-L_min' => 47.5,
                'LK-L_max' => 49.8,
                'LK-P_min' => 46.8,
                'LK-P_max' => 49.1,
            ],
            [
                'usia' => 39,
                'BB-L_min' => 13.1,
                'BB-L_max' => 16.4,
                'BB-P_min' => 11.2,
                'BB-P_max' => 15.9,
                'TB-L_min' => 98.1,
                'TB-L_max' => 106.3,
                'TB-P_min' => 96.0,
                'TB-P_max' => 104.5,
                'LK-L_min' => 47.6,
                'LK-L_max' => 49.9,
                'LK-P_min' => 46.9,
                'LK-P_max' => 49.2,
            ],
            [
                'usia' => 40,
                'BB-L_min' => 13.2,
                'BB-L_max' => 16.6,
                'BB-P_min' => 11.3,
                'BB-P_max' => 16.0,
                'TB-L_min' => 98.8,
                'TB-L_max' => 107.0,
                'TB-P_min' => 96.7,
                'TB-P_max' => 105.3,
                'LK-L_min' => 47.7,
                'LK-L_max' => 50.0,
                'LK-P_min' => 47.0,
                'LK-P_max' => 49.3,
            ],
            [
                'usia' => 41,
                'BB-L_min' => 13.3,
                'BB-L_max' => 16.8,
                'BB-P_min' => 11.4,
                'BB-P_max' => 16.2,
                'TB-L_min' => 99.5,
                'TB-L_max' => 107.8,
                'TB-P_min' => 97.5,
                'TB-P_max' => 106.1,
                'LK-L_min' => 47.8,
                'LK-L_max' => 50.1,
                'LK-P_min' => 47.1,
                'LK-P_max' => 49.4,
            ],
            [
                'usia' => 42,
                'BB-L_min' => 13.4,
                'BB-L_max' => 17.0,
                'BB-P_min' => 11.5,
                'BB-P_max' => 16.3,
                'TB-L_min' => 100.2,
                'TB-L_max' => 108.5,
                'TB-P_min' => 98.3,
                'TB-P_max' => 106.9,
                'LK-L_min' => 47.9,
                'LK-L_max' => 50.2,
                'LK-P_min' => 47.2,
                'LK-P_max' => 49.5,
            ],
            [
                'usia' => 43,
                'BB-L_min' => 13.5,
                'BB-L_max' => 17.1,
                'BB-P_min' => 11.6,
                'BB-P_max' => 16.5,
                'TB-L_min' => 100.9,
                'TB-L_max' => 109.3,
                'TB-P_min' => 99.0,
                'TB-P_max' => 107.7,
                'LK-L_min' => 48.0,
                'LK-L_max' => 50.3,
                'LK-P_min' => 47.3,
                'LK-P_max' => 49.6,
            ],
            [
                'usia' => 44,
                'BB-L_min' => 13.6,
                'BB-L_max' => 17.3,
                'BB-P_min' => 11.7,
                'BB-P_max' => 16.7,
                'TB-L_min' => 101.6,
                'TB-L_max' => 110.0,
                'TB-P_min' => 99.8,
                'TB-P_max' => 108.5,
                'LK-L_min' => 48.1,
                'LK-L_max' => 50.4,
                'LK-P_min' => 47.4,
                'LK-P_max' => 49.7,
            ],
            [
                'usia' => 45,
                'BB-L_min' => 13.7,
                'BB-L_max' => 17.4,
                'BB-P_min' => 11.8,
                'BB-P_max' => 16.8,
                'TB-L_min' => 102.3,
                'TB-L_max' => 110.8,
                'TB-P_min' => 100.5,
                'TB-P_max' => 109.3,
                'LK-L_min' => 48.2,
                'LK-L_max' => 50.5,
                'LK-P_min' => 47.5,
                'LK-P_max' => 49.8,
            ],
            [
                'usia' => 46,
                'BB-L_min' => 13.8,
                'BB-L_max' => 17.6,
                'BB-P_min' => 11.9,
                'BB-P_max' => 17.0,
                'TB-L_min' => 103.0,
                'TB-L_max' => 111.5,
                'TB-P_min' => 101.3,
                'TB-P_max' => 110.0,
                'LK-L_min' => 48.3,
                'LK-L_max' => 50.6,
                'LK-P_min' => 47.6,
                'LK-P_max' => 49.9,
            ],
            [
                'usia' => 47,
                'BB-L_min' => 13.9,
                'BB-L_max' => 17.7,
                'BB-P_min' => 12.0,
                'BB-P_max' => 17.1,
                'TB-L_min' => 103.7,
                'TB-L_max' => 112.3,
                'TB-P_min' => 102.0,
                'TB-P_max' => 110.8,
                'LK-L_min' => 48.4,
                'LK-L_max' => 50.7,
                'LK-P_min' => 47.7,
                'LK-P_max' => 50.0,
            ],
            [
                'usia' => 48,
                'BB-L_min' => 14.0,
                'BB-L_max' => 17.9,
                'BB-P_min' => 12.1,
                'BB-P_max' => 17.3,
                'TB-L_min' => 104.4,
                'TB-L_max' => 113.0,
                'TB-P_min' => 102.8,
                'TB-P_max' => 111.6,
                'LK-L_min' => 48.5,
                'LK-L_max' => 50.8,
                'LK-P_min' => 47.8,
                'LK-P_max' => 50.1,
            ],
            [
                'usia' => 49,
                'BB-L_min' => 14.1,
                'BB-L_max' => 18.0,
                'BB-P_min' => 12.2,
                'BB-P_max' => 17.4,
                'TB-L_min' => 105.1,
                'TB-L_max' => 113.7,
                'TB-P_min' => 103.5,
                'TB-P_max' => 112.3,
                'LK-L_min' => 48.6,
                'LK-L_max' => 50.9,
                'LK-P_min' => 47.9,
                'LK-P_max' => 50.2,
            ],
            [
                'usia' => 50,
                'BB-L_min' => 14.2,
                'BB-L_max' => 18.2,
                'BB-P_min' => 12.3,
                'BB-P_max' => 17.6,
                'TB-L_min' => 105.7,
                'TB-L_max' => 114.5,
                'TB-P_min' => 104.2,
                'TB-P_max' => 113.1,
                'LK-L_min' => 48.7,
                'LK-L_max' => 51.0,
                'LK-P_min' => 48.0,
                'LK-P_max' => 50.3,
            ],
            [
                'usia' => 51,
                'BB-L_min' => 14.3,
                'BB-L_max' => 18.3,
                'BB-P_min' => 12.4,
                'BB-P_max' => 17.7,
                'TB-L_min' => 106.4,
                'TB-L_max' => 115.2,
                'TB-P_min' => 105.0,
                'TB-P_max' => 113.9,
                'LK-L_min' => 48.8,
                'LK-L_max' => 51.1,
                'LK-P_min' => 48.1,
                'LK-P_max' => 50.4,
            ],
            [
                'usia' => 52,
                'BB-L_min' => 14.4,
                'BB-L_max' => 18.4,
                'BB-P_min' => 12.5,
                'BB-P_max' => 17.9,
                'TB-L_min' => 107.1,
                'TB-L_max' => 115.9,
                'TB-P_min' => 105.7,
                'TB-P_max' => 114.6,
                'LK-L_min' => 48.9,
                'LK-L_max' => 51.2,
                'LK-P_min' => 48.2,
                'LK-P_max' => 50.5,
            ],
            [
                'usia' => 53,
                'BB-L_min' => 14.5,
                'BB-L_max' => 18.6,
                'BB-P_min' => 12.6,
                'BB-P_max' => 18.0,
                'TB-L_min' => 107.7,
                'TB-L_max' => 116.6,
                'TB-P_min' => 106.4,
                'TB-P_max' => 115.4,
                'LK-L_min' => 49.0,
                'LK-L_max' => 51.3,
                'LK-P_min' => 48.3,
                'LK-P_max' => 50.6,
            ],
            [
                'usia' => 54,
                'BB-L_min' => 14.6,
                'BB-L_max' => 18.7,
                'BB-P_min' => 12.7,
                'BB-P_max' => 18.2,
                'TB-L_min' => 108.3,
                'TB-L_max' => 117.3,
                'TB-P_min' => 107.1,
                'TB-P_max' => 116.1,
                'LK-L_min' => 49.1,
                'LK-L_max' => 51.4,
                'LK-P_min' => 48.4,
                'LK-P_max' => 50.7,
            ],
            [
                'usia' => 55,
                'BB-L_min' => 14.7,
                'BB-L_max' => 18.9,
                'BB-P_min' => 12.8,
                'BB-P_max' => 18.3,
                'TB-L_min' => 108.9,
                'TB-L_max' => 118.0,
                'TB-P_min' => 107.8,
                'TB-P_max' => 116.8,
                'LK-L_min' => 49.2,
                'LK-L_max' => 51.5,
                'LK-P_min' => 48.5,
                'LK-P_max' => 50.8,
            ],
            [
                'usia' => 56,
                'BB-L_min' => 14.8,
                'BB-L_max' => 19.0,
                'BB-P_min' => 12.9,
                'BB-P_max' => 18.5,
                'TB-L_min' => 109.5,
                'TB-L_max' => 118.7,
                'TB-P_min' => 108.5,
                'TB-P_max' => 117.5,
                'LK-L_min' => 49.3,
                'LK-L_max' => 51.6,
                'LK-P_min' => 48.6,
                'LK-P_max' => 50.9,
            ],
            [
                'usia' => 57,
                'BB-L_min' => 14.9,
                'BB-L_max' => 19.1,
                'BB-P_min' => 13.0,
                'BB-P_max' => 18.6,
                'TB-L_min' => 110.1,
                'TB-L_max' => 119.4,
                'TB-P_min' => 109.2,
                'TB-P_max' => 118.3,
                'LK-L_min' => 49.4,
                'LK-L_max' => 51.7,
                'LK-P_min' => 48.7,
                'LK-P_max' => 51.0,
            ],
            [
                'usia' => 58,
                'BB-L_min' => 15.0,
                'BB-L_max' => 19.3,
                'BB-P_min' => 13.1,
                'BB-P_max' => 18.8,
                'TB-L_min' => 110.7,
                'TB-L_max' => 120.0,
                'TB-P_min' => 109.8,
                'TB-P_max' => 119.0,
                'LK-L_min' => 49.5,
                'LK-L_max' => 51.8,
                'LK-P_min' => 48.8,
                'LK-P_max' => 51.1,
            ],
            [
                'usia' => 59,
                'BB-L_min' => 15.1,
                'BB-L_max' => 19.4,
                'BB-P_min' => 13.2,
                'BB-P_max' => 18.9,
                'TB-L_min' => 111.3,
                'TB-L_max' => 120.7,
                'TB-P_min' => 110.5,
                'TB-P_max' => 119.7,
                'LK-L_min' => 49.6,
                'LK-L_max' => 51.9,
                'LK-P_min' => 48.9,
                'LK-P_max' => 51.2,
            ],
            [
                'usia' => 60,
                'BB-L_min' => 15.2,
                'BB-L_max' => 19.5,
                'BB-P_min' => 13.3,
                'BB-P_max' => 19.1,
                'TB-L_min' => 111.9,
                'TB-L_max' => 121.4,
                'TB-P_min' => 111.2,
                'TB-P_max' => 120.4,
                'LK-L_min' => 49.7,
                'LK-L_max' => 52.0,
                'LK-P_min' => 49.0,
                'LK-P_max' => 51.3,
            ],
        ]);
    }
}
